### ISSUE TITLE
`yarnInstallWithRetries/action.yml` ignores input `ignore-scripts`

### ISSUE THREAD

**Issue by Jucamola** [salesforcecli/github-workflows#96]
The `--ignore-scripts` flag is always added because expressions evaluate the input as a string, so 'false' is true. It can be fixed just by changing it to `${{ inputs.ignore-scripts == 'true' && '--ignore-scripts' || '' }}`

I didn't check, but I think there could be the same problem [here](https://github.com/salesforcecli/github-workflows/blob/fcf296caebb028dbf15ae4846da38bd605a7d0f9/.github/workflows/npmPublish.yml#L109), [here](https://github.com/salesforcecli/github-workflows/blob/fcf296caebb028dbf15ae4846da38bd605a7d0f9/.github/workflows/externalCompile.yml#L86) and [here](https://github.com/salesforcecli/github-workflows/blob/fcf296caebb028dbf15ae4846da38bd605a7d0f9/.github/workflows/automerge.yml#L37)

**Comment by iowillhoit** [comment]
Hey @Jucamola, thanks for the issue. This was fixed yesterday here: https://github.com/salesforcecli/github-workflows/pull/99

The other workflows you linked to will work as expected because they are `Workflows` and not `Actions`. Workflow inputs are able to be typed where Action inputs can only be strings.

Example with the `npmPublish` workflows:
- `sign` is a `boolean` [here](https://github.com/salesforcecli/github-workflows/blob/fcf296caebb028dbf15ae4846da38bd605a7d0f9/.github/workflows/npmPublish.yml#L21)
- It is used [here](https://github.com/salesforcecli/github-workflows/blob/fcf296caebb028dbf15ae4846da38bd605a7d0f9/.github/workflows/npmPublish.yml#L109) in the same workflow
- [Here is an example](https://github.com/salesforcecli/sf-plugins-core/blob/2bbb34b01ead60b7336367332c3f11479959f96d/.github/workflows/onRelease.yml#L26-L30) where we use the `npmPublish` workflow and do not pass `sign: true`
- [Here is an execution of that workflow](https://github.com/salesforcecli/sf-plugins-core/actions/runs/8904636685/job/24454205202#step:7:6) and you can see that the `--sign` flag is not sent to the `sf-release npm:package:release` command. Here is a screenshot of the same since GHAs don't make their logs available for very long:
<img width="1232" alt="Screenshot 2024-05-10 at 11 46 45 AM" src="https://github.com/salesforcecli/github-workflows/assets/1715111/4e1b27f8-8104-4b34-b759-dd60e680f597">
